import Head from 'next/head';
import Info from '../components/Info';
import Hero from '../components/Hero';

export default function Home() {
    return (
        <div>
            <Head>
                <title>CBRecruitment</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Hero />
            <Info />
        </div>
    );
}
